services:
  - type: worker
    name: telegram-moderation-bot
    env: python
    plan: free
    buildCommand: |
      python predeploy.py && \
      pip install --no-cache-dir --only-binary=:all: -r requirements.txt
    startCommand: "python run.py"
