services:
  - type: web
    name: telegram-moderation-bot
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir --only-binary=:all: -r requirements.txt
    startCommand: python -m run
